//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int IdVenta { get; set; }
        public int IdZapato { get; set; }
        public int IdTienda { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaVenta { get; set; }
    
        public virtual Tiendas Tiendas { get; set; }
        public virtual Zapatos Zapatos { get; set; }
    }
}
