//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zapatos()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int IdZapato { get; set; }
        public string Marca { get; set; }
        public string Estilo { get; set; }
        public string Tamano { get; set; }
        public Nullable<int> ParaQuien { get; set; }
        public Nullable<double> PrecioUnitario { get; set; }
        public Nullable<bool> Extento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
